### ISSUE TITLE
No leading zero

### ISSUE THREAD

**Issue by kristoforsalmin** [kraftvaerk/stylelint-config-kraftvaerk#5]
Hi 😀 Why not have a leading zero? Some people say that by dropping loading zero you can save some bytes and that's right, but we compress our CSS nowadays, so maybe we can just use more human-readable format? What do you think?

**Comment by mi2oon** [comment]
@racse1 I don't mind either. I've always used no leading zero. I guess my brain has already been wired to compression mode. 😉 Lets see what the others think. @PelleLagermann @rammi987 @rcdk @AnastasiaRed @akoreshkov @NinjaWinja

**Comment by kristoforsalmin** [comment]
@mi2oon I think I'm going to close this one unless we get other people to upvote this change. Right now it looks like I'm the only one who sort of wants it 🙃

**Comment by mi2oon** [comment]
@kristoforsalmin That's fine ;)
