### ISSUE TITLE
Enforce consistent line endings

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/stylelint-config-kraftvaerk#9]
Hi, currently we use `lf` in `.editorconfig`, which causes some inconvenience on Windows machines. Perhaps, we should just use `crlf` (everyone in KV uses Windows anyway). This way we'll be also aligned with generator-rammevaerk.

**Comment by mi2oon** [comment]
@racse1 Ture, I think everyone uses Windows machines at work. However, we do have a few like me who uses MacOS at home. Also we get freelancers from time to time who also uses MacOS.
